### ISSUE TITLE
Interactive example hangs on connect

### ISSUE THREAD

**Issue by taheris** [GENIVI/rvi_lib#17]
This is probably due to some incorrect configuration on my side, but after a few hours of working on this I've yet to be able to get the interactive C client communicating with rvi_core.

In terms of config, the backend is set up [like so](https://gist.github.com/taheris/30e44f869dd26e454dae3a4348644bb3). For testing, the insecure keys are used from the rvi_core develop branch, and `insecure_root_cert.crt` is added to the root CA list. Additionally, the exo dependency `host.{cert,key}` is set to use `insecure_device_cert.{crt,key}` as this certificate was also expired.

On the client side, a new set of development credentials signed by the same root CA were created (along with a JWT). Openssl verification (via `openssl s_client -CAfile priv/certificates/insecure_root_cert.crt -connect 127.0.0.1:8801 < /dev/null`) returns OK.

When running the interactive example however the client hangs when trying to connect to 127.0.0.1 on port 8801. There is no log output on the server side (although a `no case clause matching` crash report will be generated when connecting to port 8807). Any further help getting this set up would be appreciated.

**Comment by tjamison** [comment]
It looks like your backend RVI core is running on ports 9000-9011. From lines 123-128, the TLS connection is expected on ports 9010 and 9011, while server_opts indicates it's listening on 9010. So try connecting to 127.0.0.1:9010.

**Comment by taheris** [comment]
I forgot to mention that the `RVI_PORT` environment variable is set to 8800 on startup so the fallback value of 9000 will not be triggered. Your pointer to port 9010 specifically was helpful though, as the interactive example now works as intended after exposing the equivalent (8810) in the docker-compose startup config. Thanks for your help.
