### ISSUE TITLE
Announced services newer calls 

### ISSUE THREAD

**Issue by patriotyk** [GENIVI/rvi_lib#19]
I have tried this library to connect to the rvi node, builded with docker-compose from https://github.com/advancedtelematic/rvi_sota_server/, and successfully connected, and also I can register all services, but /sota/notify newer calls. I created vehicle in web admin, and added package. Also I tried lot of combinations of id in config.json: 
genivi.org/vin/uuid_from_web_admin_vehicle_page_url
genivi.org/vin/name_from_web_admin_vehicle_page_url
genivi.org/device/uuid_from_web_admin_vehicle_page_url
genivi.org/device/name_from_web_admin_vehicle_page_url
genivi.org/client/uuid_from_web_admin_vehicle_page_url
genivi.org/client/name_from_web_admin_vehicle_page_url
But those did not help.
Also I have found exception in rvi_core logs, this exception happens when I connect to the node from rvi_lib:

`rvi_backend_1      | (rvi@2b3b745612a8)1> 2017-01-18 21:38:57.240 [warning] <0.244.0>@rvi_common:get_json_element:340 get_json_element(): Unknown call structure; Path: [<<"rvi_log_id">>] | JSON: 123
rvi_backend_1      | (rvi@2b3b745612a8)1> 2017-01-18 21:38:57.241 [error] <0.244.0> gen_server <0.244.0> terminated with reason: bad argument in call to lists:keyfind(<<"cmd">>, 1, 123) in dlink_tls_rpc:opt/3 line 815
rvi_backend_1      | (rvi@2b3b745612a8)1> 2017-01-18 21:38:57.243 [error] <0.244.0> CRASH REPORT Process <0.244.0> with 0 neighbours exited with reason: bad argument in call to lists:keyfind(<<"cmd">>, 1, 123) in dlink_tls_rpc:opt/3 line 815`

I am not sure is it really bug in rvi_lib or maybe I am doing something wrong?

**Comment by tjamison** [comment]
Hi patriotyk, can you post the config information for the rvi_core instance? I have seen similar errors when the backend is configured to use msgpack as the encoding rather than json. 

For comparison: 

- https://github.com/GENIVI/rvi_core/blob/develop/priv/test_config/tls_backend.config uses msgpack
- https://github.com/GENIVI/rvi_core/blob/develop/priv/test_config/tlsj_backend.config uses json

**Comment by patriotyk** [comment]
Hi @tjamison unfortunately it is configured to use json,  this is my [config](https://nomakler.com.ua/media/tmp/rvi.config)

**Comment by tjamison** [comment]
Hi @patriotyk, after checking in with @uwiger, he reports that:

> In order to use JSON, since msgpack is the default, you have to add {packet_mod, dlink_data_json}
i.e.:
```
     { dlink_tls_rpc, gen_server,
     [
      { json_rpc_address, { MyIP, MyPort+11} },
      { server_opts, [ {port, MyPort+10} ]},
      { packet_mod, dlink_data_json }
     ]
   }
```

For the configuration you specified, the diff is:

```
diff --git a/rvi.config b/rvi.config
index 210b011..955d2d0 100644
--- a/rvi.config
+++ b/rvi.config
@@ -332,7 +332,8 @@ LogLevel = Env("RVI_LOGLEVEL", notice).
            { dlink_tls_rpc, gen_server,
              [
               { json_rpc_address, { MyIP, MyPort+11} },
-              { server_opts, [ {port, MyPort+10} ]}
+              { server_opts, [ {port, MyPort+10} ]},
+           { packet_mod, dlink_data_json }
              ]
            }
          ]
```

**Comment by uwiger** [comment]
Note that I will do my best to significantly simplify the config in the next release. :)

**Comment by patriotyk** [comment]
Thank You for your help, but it looks like this didn't help, I have changed config, but got the same error. This is my [crash.log](https://nomakler.com.ua/media/tmp/crash.log), it has much more information, and from this log I see that msgpack is used, but I have changed configuration as You wrote.

**Comment by patriotyk** [comment]
Also I have found that rvi_lib doesn't handle errors when connects to the node, for example rviProcessInput returns error, because server returns empty response, but rvi_lib didn't check it and reports successful connection establishment.

**Comment by patriotyk** [comment]
@tjamison @uwiger  thank You for help, `{ packet_mod, dlink_data_json }` have fixed the problem. I did changes to /etc/rvi/rvi.config because have found that systemV service script use it, but in my case rvi runs from `run_rvi.sh` script that uses `backend.rvi.config`

**Comment by patriotyk** [comment]
Sorry, reopening, because we really have an bug with calling callback on 32 bit systems.

**Comment by tjamison** [comment]
Hi @patriotyk, I merged your PR. Does that resolve the issue?

**Comment by patriotyk** [comment]
Yes, thank You.
